### ISSUE TITLE
Before / After pseudo elements

### ISSUE THREAD

**Issue by matthijs110** [MathiasGilson/Tailwind-Styled-Component#23]
How can I define (dynamic) pseudo-elements (`:before` or `:after`)? 

I know this is not natively possible in Tailwind yet, but I was wondering if there is a way to work around this.

I am trying to achieve the following:
```scss
.element:before {
    color: $color;
}
```

where `$color` should be a dynamic variable.
